package com.softvision.ipm.pms.common.constants;

public enum EmailType {
    APPRAISAL_CYCLE_KICK_OFF,
    APPRAISAL_CYCLE_CONCLUDE,

    ENABLE_EMPLOYEE_APPRAISAL,
    CHANGE_MANAGER,
    EMPLOYEE_SUBMITED,
    SEND_REMINDER_MGR_TO_EMP,
    REVERT_TO_SELF_SUBMISSION,
    MANAGER_REVIEW_COMPLETED,
    AGREED_WITH_REVIEW,
    DISAGREED_WITH_REVIEW,
    MANAGER_REVIEW_UPDATED,
    ASSIGNMENT_CONCLUDED,

    SEND_REMINDER_HR_TO_EMP,
    SEND_REMINDER_HR_TO_MGR,
}
