-- REVOKE ALL ON DATABASE sv_pms FROM sv_pms_app;
ALTER DATABASE sv_pms OWNER TO sv_pms_app;

--GRANT CONNECT ON DATABASE SV_PMS TO sv_pms_app;
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sv_pms_app;
--GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sv_pms_app;